# Generated by Django 3.1.2 on 2020-10-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salasah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='toko',
            field=models.ManyToManyField(to='Salasah.Toko'),
        ),
        migrations.RemoveField(
            model_name='onlineorder',
            name='penerima',
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='penerima',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='OfflineOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=70)),
                ('no_telepon', models.CharField(max_length=13)),
                ('keterangan', models.TextField()),
                ('tanggal', models.DateTimeField()),
                ('kode_barang', models.ManyToManyField(to='Salasah.KodeBarang')),
            ],
        ),
    ]
