# Generated by Django 3.1.2 on 2020-10-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salasah', '0002_auto_20201018_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='jasa_kirim',
            field=models.CharField(choices=[('Ninja Xpress', 'Ninja Xpress'), ('J&T Express', 'J&T Express'), ('JNE EXPRESS', 'JNE EXPRESS'), ('SICEPAT', 'SICEPAT'), ('TiKi', 'TiKi'), ('Pos Indonesia', 'Pos Indonesia'), ('anteraja', 'anteraja'), ('GrabExpress', 'GrabExpress'), ('Gojek', 'Gojek')], max_length=100, null=True),
        ),
    ]
